### ISSUE TITLE
urgente fix su forEach in getCart 

### ISSUE THREAD

**Issue by mcanovese** [SWException/carts#2]
E' necessario mitigare tempestivamente i disagi causati dall' esecuzione di getCart, più precisamente il ciclo forEach() nel model. 
Va adattato con un foreach asincrono che allo stato attuale non abbiamo idea di come fare.

Sarà bene porre rimedio in tempi stretti al fine di non bloccare ulteriormente il processo di test di order.

**Comment by ivanfurlan** [comment]
@micheleveronesi Confidiamo nelle tue competenze applicate al problema per arrivare ad una soluzione just in time per il colloquio di RQ

**Comment by ivanfurlan** [comment]
Non è contemplato l'uso di codice come "as unknown as Promise<T>" o similari

**Comment by mcanovese** [comment]
Sarà bene lavorare ragionatamente piuttosto che in fretta

**Comment by ivanfurlan** [comment]
Apprezzabile la suddivisione del lavoro tra membri del gruppo, ma non è ragionevole che si possano concentrare tutte le risorse su un unico task senza che ci siano conflitti in esso.

**Comment by mveronesi** [comment]
@NikySky sarà bene che questa issue sia chiusa domani all'alba. Buonanotte.

**Comment by mcanovese** [comment]
Sarà bene tenere aggiornato questo cruscotto per tenere aggiornati tutti parallelamente

**Comment by mveronesi** [comment]
Però facendo push, e non pull

**Comment by mveronesi** [comment]
Evviva le iterazioni distruttive. La messa è finita.

**Comment by ivanfurlan** [comment]
Evitiamo il più possibile un metodo di sviluppo agile

**Comment by ivanfurlan** [comment]
> Evviva le iterazioni distruttive. La messa è finita.

Auguri

**Comment by mcanovese** [comment]
@NikySky Puoi fornirci un feedback just in time ?
