### ISSUE TITLE
Implementare carrello guest

### ISSUE THREAD

**Issue by mveronesi** [SWException/carts#5]

**Comment by mveronesi** [comment]
@ivanfurlan funzionalità implementata, adesso le API getCart e addToCart se invocate senza guestToken e Authorization generano un nuovo carrello con id del tipo "guest_"+uuidv4()

**Comment by ivanfurlan** [comment]
Ok, quindi manca il "trasferimento" da utente guest ad autenticato?

**Comment by mveronesi** [comment]
@ivanfurlan giusto, avevo dimenticato. Dopo pranzo penso ad una soluzione e implemento.
