### ISSUE TITLE
Controllare quantità disponibili

### ISSUE THREAD

**Issue by mveronesi** [SWException/carts#6]
Controllare le quantità quando ritorno il carrello

**Comment by mveronesi** [comment]
@ivanfurlan funzionalità implementata, modifichiamo l'interfaccia di getCart per segnalare la modifica automatica del carrello effettuata da getCart in caso di quantità non più disponibile?

**Comment by ivanfurlan** [comment]
Potrebbe essere buona cosa. Si potrebbe mettere anche solamente in message "Alcuni elementi del carrello sono stati rimossi o modificati in quanto non più presenti nella quantità desiderata", mentre se è tutto ok message resta vuoto

**Comment by mveronesi** [comment]
Si facciamo così @ivanfurlan 
Dopo pranzo implemento
